version: '3.4'

services:
  apiworksfromdwpuk:
    image: api_dwp_jobs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_dwp_jobs
    ports:
      - 8000:8000
