version: '3.4'

services:
  api_dwp_jobs:
    image: api_dwp_jobs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_dwp_jobs
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
