version: '3.4'

services:
  apiworksfromdwpuk:
    image: apiworksfromdwpuk
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiworksfromdwpuk
    ports:
      - 8000:90
